// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';
import { getSessionToken } from '../../lib/auth';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

const authAwareFetch: typeof fetch = async (input, init) => {
  const sessionToken = getSessionToken();
  const headers = new Headers(init?.headers || {});

  if (sessionToken) {
    headers.set('x-session-token', sessionToken);
  } else {
    headers.delete('x-session-token');
  }

  return fetch(input, { ...init, headers });
};

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  },
  global: {
    fetch: authAwareFetch,
  },
});

export const syncSupabaseSessionToken = () => {
  const sessionToken = getSessionToken();
  const value = sessionToken || '';

  (supabase as any).__customHeaders = {
    ...(supabase as any).__customHeaders,
    'x-session-token': value,
  };

  if ((supabase as any).rest?.headers) {
    (supabase as any).rest.headers['x-session-token'] = value;
  }

  if ((supabase as any).realtime?.headers) {
    (supabase as any).realtime.headers['x-session-token'] = value;
  }
};